#
# Ops-Pipeline - Templates for automating the production and consumption of images
# and containers.
#
# Copyright 2016 Capital One Services, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

cfg = {}
cfg[:cpus]        ||= "2"
cfg[:memory]      ||= "4096"
cfg[:gui]         ||= false
cfg[:box]         ||= "opspipeline/headless-ubuntu"
cfg[:nfs]         ||= true

Vagrant.configure(2) do |config|
  config.vm.box = cfg[:box]
  config.vm.synced_folder ".", "/vagrant", type: "nfs" if cfg[:nfs]

  config.vm.define "builder" do |vmconfig|

    vmconfig.vm.provider "vmware_fusion" do |v|
      v.vmx["numvcpus"] = cfg[:cpus]
      v.vmx["memsize"]  = cfg[:memory]
      v.gui = cfg[:gui]
      v.vmx["vhv.enable"] = "TRUE"
    end

    vmconfig.vm.provider 'vmware_appcatalyst' do |v|
      v.vmx['numvcpus'] = cfg[:cpus]
      v.vmx['memsize']  = cfg[:memory]
      v.gui = "false"
      v.vmx["vhv.enable"] = "TRUE"
    end
  end

  config.berkshelf.enabled = true
  config.vm.provision "chef_solo" do |chef|
    chef.json = {
       'jenkins-job' => {
          'job-templates' => {
          'test_sonar' => 'test_sonar.xml.erb'
        }
      },
      "vmware_workstation" => {
        "serial_number" => "this-should-be-a-valid-serial-number"
      }
    }
    chef.roles_path = 'provision/chef/roles'
    chef.data_bags_path = "provision/chef/data_bags"
    chef.add_role 'jenkins-master'
    chef.add_role 'opspipeline-headless'
  end
end