=begin
/*************************IZANAMEE-LICENSE-START*********************************
 * Copyright 2015 CapitalOne, LLC.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *************************IZANAMEE-LICENSE-END*********************************/
=end

# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative '../../../lib/izanamee'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Init Izanamee config
  Izanamee.config = config
  Izanamee::VMHelper.guest_os = Izanamee::VMHelper.supported_systems[:ubuntu_trusty]

  #####################################################################
  # Check proxy settings (requires vagrant-proxyconf plugin)
  #Izanamee::ProxyHelper.check_for_proxy_envvars
  #Izanamee::ProxyHelper.set_proxyconfig

  #####################################################################
  # Vagrant box settings

  # Initialize to the base Ubuntu 14.04LTS Server image
  Izanamee.config.vm.box = Izanamee::VMHelper.guest_os.vagrant_box_name

  #####################################################################
  # VirtualBox settings

  # Configure VirtualBox startup params
  Izanamee.config.vm.provider :virtualbox do |vb|
    vb.name = 'base-xubuntu'
    vb.memory = 8192
    vb.cpus = 2
    vb.gui = true
    vb.customize ['modifyvm', :id, '--accelerate3d', 'on']
    vb.customize ['modifyvm', :id, '--vram', '64']
  end

  # Set up vm tweaks
  Izanamee::VMHelper.set_natdnsproxy
  Izanamee::VMHelper.fix_ubuntu_ssh_tty

  ##########################################################################
  # Provision window manager and update VirtualBox Guest Additions
  Izanamee::Provisioners::WMInstaller.provision
  Izanamee::Provisioners.purge_config_credentials

end