cfg = {}
cfg[:cpus]        ||= '2'
cfg[:memory]      ||= '8096'
cfg[:gui]         ||= false
cfg[:box]         ||= 'opspipeline/headless'
cfg[:nfs]         ||= true

Vagrant.configure(2) do |config|
  config.vm.box = cfg[:box]
  config.vm.synced_folder '.', '/vagrant', type: 'nfs' if cfg[:nfs]

  config.vm.define 'jenkinsonar' do |vmconfig|
    vmconfig.vm.provider 'vmware_fusion' do |v|
      v.vmx['numvcpus'] = cfg[:cpus]
      v.vmx['memsize']  = cfg[:memory]
      v.gui = cfg[:gui]
      v.vmx['vhv.enable'] = 'TRUE'
    end

    vmconfig.vm.provider 'vmware_appcatalyst' do |v|
      v.vmx['numvcpus'] = cfg[:cpus]
      v.vmx['memsize']  = cfg[:memory]
      v.gui = 'false'
      v.vmx['vhv.enable'] = 'TRUE'
    end
  end

  config.berkshelf.enabled = true
  config.vm.provision 'chef_solo' do |chef|
    chef.json = {
      'jenkins-job' => {
        'job-files' => {
          'test_sonar' => 'test_sonar.xml'
        }
      }
    }
    chef.roles_path = 'provision/chef/roles'
    chef.data_bags_path = 'provision/chef/data_bags'
    chef.add_role 'jenkinsonar'
  end
end
