#
# Ops-Pipeline - Templates for automating the production and consumption of images
# and containers.
#
# Copyright 2016 Capital One Services, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
cfg = {}
cfg[:cpus] ||= '2'
cfg[:memory] ||= '8096'
cfg[:gui] ||= true
cfg[:os] ||= 'centos'
cfg[:role] ||= 'desktop'
cfg[:org] ||= 'opspipeline'
cfg[:hostname] ||= "#{cfg[:role]}-#{cfg[:os]}"
cfg[:box] ||= "#{cfg[:org]}/#{cfg[:role]}-#{cfg[:os]}"
cfg[:nfs] ||= true

Vagrant.configure('2') do |config|
  config.vm.box = cfg[:box]
  config.vm.synced_folder '.', '/vagrant', type: 'nfs' if cfg[:nfs]

  config.vm.hostname = cfg[:hostname]
  config.vm.define cfg[:hostname] do |vmconfig|
    vmconfig.vm.provider 'vmware_fusion' do |v|
      v.vmx['numvcpus'] = cfg[:cpus]
      v.vmx['memsize']  = cfg[:memory]
      v.gui = cfg[:gui]
      v.vmx['vhv.enable'] = 'TRUE'
    end

    vmconfig.vm.provider 'vmware_appcatalyst' do |v|
      v.vmx['numvcpus'] = cfg[:cpus]
      v.vmx['memsize']  = cfg[:memory]
      v.gui = 'false'
      v.vmx['vhv.enable'] = 'TRUE'
    end
  end

  # Uncomment to add port-forwarding
  #config.vm.network "forwarded_port", guest: 2003, host: 12003, protocol: "tcp"
end