cfg = {}
cfg[:cpus] ||= '2'
cfg[:memory] ||= '8096'
cfg[:gui] ||= true
cfg[:os] ||= 'centos'
cfg[:role] ||= 'desktop'
cfg[:org] ||= 'opspipeline'
cfg[:hostname] ||= "#{cfg[:role]}-#{cfg[:os]}"
cfg[:box] ||= "#{cfg[:org]}/#{cfg[:role]}-#{cfg[:os]}"
cfg[:nfs] ||= true

Vagrant.configure('2') do |config|
  config.vm.box = cfg[:box]
  config.vm.synced_folder '.', '/vagrant', type: 'nfs' if cfg[:nfs]

  config.vm.hostname = cfg[:hostname]
  config.vm.define cfg[:hostname] do |vmconfig|
    vmconfig.vm.provider 'vmware_fusion' do |v|
      v.vmx['numvcpus'] = cfg[:cpus]
      v.vmx['memsize']  = cfg[:memory]
      v.gui = cfg[:gui]
      v.vmx['vhv.enable'] = 'TRUE'
    end

    vmconfig.vm.provider 'vmware_appcatalyst' do |v|
      v.vmx['numvcpus'] = cfg[:cpus]
      v.vmx['memsize']  = cfg[:memory]
      v.gui = 'false'
      v.vmx['vhv.enable'] = 'TRUE'
    end
  end

  # Uncomment to add port-forwarding
  #config.vm.network "forwarded_port", guest: 2003, host: 12003, protocol: "tcp"
end
